{"uid":"e0437dc14f7dbd55","name":"Verify login with invalid combinations of email and password -- @1.3 ","fullName":"User Authentication: Verify login with invalid combinations of email and password","historyId":"bc1e0164b8efb7727aff867693479899","time":{"start":1745240421017,"stop":1745240428051,"duration":7034},"status":"failed","statusMessage":"AssertionError: AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.'\n","statusTrace":"  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"OpenCartDemoSimulation\\features\\steps\\login_steps.py\", line 49, in step_impl\n    assert \"Warning: No match for E-Mail Address and/or Password.\" in context.login_page.get_login_error(), f\"AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got '{context.login_page.get_login_error()}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.'\n","statusTrace":"  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"OpenCartDemoSimulation\\features\\steps\\login_steps.py\", line 49, in step_impl\n    assert \"Warning: No match for E-Mail Address and/or Password.\" in context.login_page.get_login_error(), f\"AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got '{context.login_page.get_login_error()}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Given I open the OpenCart login page","time":{"start":1745240423660,"stop":1745240424640,"duration":980},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"When I enter email \"EMPTY\" and password \"EMPTY\" in the login form","time":{"start":1745240424640,"stop":1745240424930,"duration":290},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"And I submit the login form","time":{"start":1745240424931,"stop":1745240425129,"duration":198},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"Then I should see an error message saying \"Warning: No match for E-Mail Address and/or Password.\"","time":{"start":1745240425129,"stop":1745240425763,"duration":634},"status":"failed","statusMessage":"AssertionError: AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.'\n","statusTrace":"  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\caioa\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"OpenCartDemoSimulation\\features\\steps\\login_steps.py\", line 49, in step_impl\n    assert \"Warning: No match for E-Mail Address and/or Password.\" in context.login_page.get_login_error(), f\"AssertionError: Expected 'Warning: No match for E-Mail Address and/or Password.', but got '{context.login_page.get_login_error()}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"hasContent":true,"stepsCount":0,"attachmentStep":false,"shouldDisplayMessage":true,"attachmentsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"stepsCount":4,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"browser"},{"name":"feature","value":"User Authentication"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"email","value":"EMPTY"},{"name":"password","value":"EMPTY"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["browser"]},"source":"e0437dc14f7dbd55.json","parameterValues":["EMPTY","EMPTY"]}